### PR TITLE
Add metadata and license

### PR DESCRIPTION
**Pull request by bryanwweber**
Adds license_file metadata and additional metadata for the project

### CODE REVIEW

**Comment by TomTranter** [comment]
Hi @bryanwweber, thanks for this pull request. Why are you removing porespy dependency though? It is necessary for examples

**Comment by bryanwweber** [comment]
Hi @TomTranter! Indeed, but the current state is a circular dependency between pytrax and PoreSpy (i.e., PoreSpy depends on having a pytrax package, and vice versa). I'm working with @ma-sadeghi to build conda packages for OpenPNM, PoreSpy and pytrax and to do that there can't be any circular dependencies. If PoreSpy is necessary to run the example, users will need to install that themselves, rather than requiring it in `setup.py`.

**Comment by TomTranter** [comment]
I was planning to make notebooks for the examples anyway so I could maybe add an install line into those if the user hasn't got porespy

**Comment by bryanwweber** [comment]
IMO it would be better to do something like:
```
try:
    import porespy as ps
except ImportError:
    print("PoreSpy must be installed for the examples. Use pip or conda to install it")
    raise
```
That way, people who don't have administrator permissions don't get a strange error from trying to install PoreSpy and the actual cause of the problem is identified. Also, some people will want to use pip, others conda, others build from source, etc.

**Comment by TomTranter** [comment]
@bryanwweber good suggestion. Is this good to be merged in now? I will create a separate branch to update examples afterwards

**Comment by bryanwweber** [comment]
@TomTranter Yes, it's good from my end. BTW, thanks for considering this! I didn't include any explanation in the first comment, just kind of dropped it on your head. I had assumed that your group would know what I was doing, it seems that was my mistake! Sorry for the missing explanation :smile:

**Comment by TomTranter** [comment]
@bryanwweber no worries, I'm not physically in Jeff's group anymore so everyone else probably knows what you're up to

**Comment by ma-sadeghi** [comment]
Sorry @TomTranter and @bryanwweber, my bad. I forgot to let Tom know what we were up to.

@TomTranter, we want to include Cantera as an OpenPNM dependency for mixtures, but since Cantera is not pip-installable yet, @bryanwweber offered to help us develop conda packages for our libraries so we can safely list Cantera as a dependency.

**Pull request merged**
